In [3]:
import numpy as np


In [34]:
#QUESTION 1
#a = np.array([[0,1,2],[3,4,5],[6,7,8]])
liste=[]

print(a.tolist())


   


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [58]:
#QUESTION 2 

#a = np.array([[0,1,2],[3,4,5],[6,7,5]])
s=0


for i in range(0,a.shape[0]):
    
        s=s+a[i][i]
        
print('somme',s)

somme 9


In [63]:
#QUESTION 3 
a = np.array([[44,99,2],[6,7,5],[6,7,5]])
x=5
liste=[]
for i in range(0,a.shape[0]):
    for j in range(0,a.shape[1]):
        if a[i][j]>x:
            print(a[i][j],' est superieur de ',x)
            

44  est superieur de  5
99  est superieur de  5
6  est superieur de  5
7  est superieur de  5
6  est superieur de  5
7  est superieur de  5


In [75]:
#Question 4
#a = np.array([[44,99,2],[6,7,5],[6,7,5]])
#b=np.array([[1,2,3],[4,5,6],[7,8,9]])

c=a+b
print(c)

        


[[ 45 101   5]
 [ 10  12  11]
 [ 13  15  14]]


In [88]:
#QUESTION 5
#a=np.array([[1,2,9],[4,5,6],[7,8,9]])
b=[]
for i in range(0,a.shape[0]):
    somme=0
    moy=0
    for j in range(0,a.shape[1]):
        somme=somme+a[i][j]
    moy=somme/a.shape[1]
    
    b.append(moy)
    
print("les moyennes :",b)

les moyennes : [4.0, 5.0, 8.0]
